version: '3.8'

services:
  
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: classpro-frontend
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_BACKEND_URL=http://backend:8080
    ports:
      - "243:243"
    depends_on:
      - backend
    volumes:
      - ./.env:/app/.env:ro
    networks:
      - classpro-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:243/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: classpro-backend
    environment:
      - GO_ENV=production
      - PORT=8080
    ports:
      - "8080:8080"
    volumes:
      - ./.env:/app/.env:ro
    networks:
      - classpro-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  classpro-network:
    driver: bridge

volumes:
  
  pass 